# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Po3zo-0rExwpbAa9dV66qD4CV92gGsua
"""

from flask import Flask, render_template_string
import cv2
from ultralytics import YOLO

app = Flask(__name__)

@app.route('/')
def home():
    return render_template_string("""
        <h2>YOLOv8 Object Detection App</h2>
        <p>This is a demo backend. Real-time camera detection works locally, not on Render.</p>
    """)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)