# -*- coding: utf-8 -*-
"""object detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsT4bB2lMMqjDPqRmsQ3Oh6Rhx-6X-FF
"""

# Install YOLOv8 (Ultralytics) and OpenCV
!pip install ultralytics opencv-python
import cv2
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break


    results = model(frame)

    annotated_frame = results[0].plot()


    cv2.imshow("Real-Time Object Detection", annotated_frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

from google.colab import files
uploaded = files.upload()

for img in uploaded.keys():
    results = model(img)
    results[0].show()